### ISSUE TITLE
Black magic casting only happens very occasionally

### ISSUE THREAD

**Issue by Imoq** [ekrividus/autoMB#15]
This may be a configuration issue, although based on the documentation I am not sure what it is. I have the following settings:

`<?xml version="1.1" ?>
<settings>
    <global>
        <cast_delay>0.25</cast_delay>
        <cast_range>22</cast_range>
        <cast_tier>1</cast_tier>
        <cast_type>spell</cast_type>
        <change_target>true</change_target>
        <check_day>false</check_day>
        <check_weather>false</check_weather>
        <disable_on_zone>false</disable_on_zone>
        <double_burst>false</double_burst>
        <double_burst_delay>1</double_burst_delay>
        <frequency>4</frequency>
        <gearswap>false</gearswap>
        <mp>100</mp>
        <show_bonus_elements>false</show_bonus_elements>
        <show_elements>false</show_elements>
        <show_skillchain>false</show_skillchain>
        <show_spell>false</show_spell>
        <step_down>0</step_down>
        <useAOE>false</useAOE>
    </global>
    <mycharacter>
        <cast_tier>4</cast_tier>
    </mycharacter>
</settings>
`

and after loading and doing the //automb start it *sometimes* casts some tier 4 magic (thunder, fire, aero) when it sees a Light SC. Since this is an exp pt, skillchains occur very often. Only one mob is being fought at a time. Sometimes there are minutes on which the character just sits there, looking at the SCs coming one after another with full MP without casting at all. Then some other times suddenly it would just start casting when detecting a SC and try to MB. Again, this is very spotty and doesn't seem to follow a pattern.

I have Windower Logger installed so I can go back and find specific log events if needed in order to debug the issue.

(Edit: the enemies are being fought in one place so it's definitely not the range as everything is closer than 5').

**Comment by ekrividus** [comment]
I think this might have been a result of a change I made for something else. A fix that broke more than it fixed. 
Can you grab an earlier version maybe:
https://github.com/ekrividus/autoMB/blob/98c63051d6c19f7da74e3b33eab87c3ae08132eb/autoMB.lua or
https://github.com/ekrividus/autoMB/blob/f292af40447bccc9f1b1d2b9f72dd1bfb2333344/autoMB.lua
and see if one or both behaves as expected. 

If neither does, or if either does, or both, let me know and I'll try to figure out what exactly in the most recent is busted. I don't currently have an active account so working on it in a more meaningful way is challenging.

**Comment by Imoq** [comment]
The first file (https://github.com/ekrividus/autoMB/blob/98c63051d6c19f7da74e3b33eab87c3ae08132eb/autoMB.lua) works wonderfully! I didn't have a chance to check the second one but if you want I can check it and report back to you.

Thank you for looking at this and for fixing it!

**Comment by ekrividus** [comment]
I'm glad to hear that. I'll take a look at the 2 this weekend and fix whatever I broke. You're welcome to test the second but certainly don't have to :)
