### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by jmhgit** [ekrividus/autoMB#17]
Loaded it, configured the settings and performed light skillchains on Locus crabs. It seemed to detect every 4th or 5th skillchain, and when it did detect the skillchain it bursted with tier I spells instead of tier 5 spells.

![image](https://github.com/ekrividus/autoMB/assets/60338633/9b8d46d5-60d6-4ac7-a79b-4f0e12254f76)
![image](https://github.com/ekrividus/autoMB/assets/60338633/c95e24cc-892d-4ae9-9eaa-f309108872d3)

**Comment by ekrividus** [comment]
Try this version: https://github.com/ekrividus/autoMB/blob/f292af40447bccc9f1b1d2b9f72dd1bfb2333344/autoMB.lua 
Rename your current settings so it generates a new settings file as a couple may changed over the versions.
Lmk if it works. If it does I'll move this version to current.
I suspect that it's a result of one of the anti-spammy pauses but as I haven't played in years I can't really test it out.

**Comment by jmhgit** [comment]
appears to be working perfectly now - thanks
