### ISSUE TITLE
Jutsu mb getting a attempt to index field '?'

### ISSUE THREAD

**Issue by Wyrmnax** [ekrividus/autoMB#2]
So, every time I try to use autoMB with Ninjutsu, I get a error on line 358

automb/automb.lua:358: attempt to index field '?' (a nil value)

Looks like it is not being able to resolve jutsu_tiers[tier].suffix for any spells

**Comment by Wyrmnax** [comment]
Issue is happening here:

if (settings.cast_tier > 0 and settings.cast_tier < 4) then

Line 681,, when trying to set up the tier

**Comment by ekrividus** [comment]
Huh, I haven't played since back in Oct. was there an update that changed something in the naming of Ninjutsus? 
I'll look into that when I get back in game.

**Comment by ekrividus** [comment]
The Ninjutsu tiers being janky "should" be fixed. I haven't made it into the game yet to test though.
