### ISSUE TITLE
Bug in Japanese environment

### ISSUE THREAD

**Issue by 2018pom** [ekrividus/autoMB#7]
It's a game from 20 years ago, but it's been less than a year since I started, so I'm enjoying it.
Thanks for the great application to use with subaccounts.
There was a problem with spell judgment in the Japanese environment, and I tried to fix it.
I think many Japanese will be pleased.

res.spells:with('name', spell)

---------------------------------------
row:255
function low_mp(spell)
	local sp = res.spells:with('en', spell)

row:271
function check_recast(spell_name)
	local recasts = windower.ffxi.get_spell_recasts()
	local spell = res.spells:with('en', spell_name)	

*** row:522 and row:530 are still res.spells:with('name', spell).

**Comment by ekrividus** [comment]
Odd, I expected that using name rather than en would have made it work better in other environments. 
I've updated it to use en everywhere.
